### ISSUE TITLE
Demo website does not work correctly

### ISSUE THREAD

**Issue by OliviaRuyinZhang** [Call-for-Code/weather-api-nodejs#18]
I followed the instruction and click "try it out" under some get request with its default example values on the demo website. None of it seems to work. Response code is 0, and the response header is {
  "error": "no response from server"
}

I also watched the video "Weather Company Data for IBM Bluemix: Deep Dive". On that video, it shows that when user click "try it out" button, the demo website is supposed to pop up a window to let users enter their username and password that they retrieved from their IBM cloud weather company provision. In fact, I don't see the pop up window after clicking "try it out" button.

I am participating in IBM call for code this year. Our team wishes to have access to the API when we are building our application. I tried to use the register forum for "Call for Code" participants to gain my API key, but I didn't receive any confirmation email. Can anyone help me to get access ? 

Thanks!

**Comment by vabarbosa** [comment]
@OliviaRuyinZhang are you asking about the "try it out" under the GET request in the API document (i.e., https://callforcode.weather.com/documentation)? if so, you first have to click the Authorize button and add your API key received after registering (i.e., https://callforcode.weather.com/register). you should receive your API key shortly after registering. i will try to see if i can track down why you didn't receive your API key and get back to you.

**Comment by OliviaRuyinZhang** [comment]
I am referring to the "try it out" on this page (https://twcservice.mybluemix.net/rest-api/#/). This is the page where the "getting started" page on IBM cloud (https://cloud.ibm.com/docs/services/Weather?topic=weather-insights_weather_overview) links us to. I tried to register my own API key last week but I don't receive any email regarding the API key since then. I also tried to register my API on the same register website, but the site shows me an error message saying "This email address is already registered" after I clicked the "submit" button.

**Comment by krook** [comment]
Is this still an open issue in need of resolution @OliviaRuyinZhang and @vabarbosa?

**Comment by OliviaRuyinZhang** [comment]
Hi team, I received my API key. I tried the API out on the demo website, most of the things seem to work normally for me. However, when I tried to use "Weather Alerts - Headlines API" with its default values on the demo website, the server response is always "TypeError: Failed to fetch". Can anyone look into this issue and see if there's any problem with the default values? Or does the Weather Alerts - Headlines API work properly? Thank you so much!
--
Link that I tried on and failed: 
https://weather.com/swagger-docs/ui/sun/v1/sunV1AlertsWeatherAlertHeadlines.json

**Comment by vabarbosa** [comment]
hi @OliviaRuyinZhang yes i am seeing the same issue when i use the Swagger docs for that API. it is not the default values nor that API since i can successfully run a sample application to call that API with the default values and do get a response. i suspect there is something else going on with that documentation page. i will see if i can figure out who to talk to about resolving that issue. thanks.

**Comment by vabarbosa** [comment]
@OliviaRuyinZhang the Swagger docs have been updated. the correct version/link for that API is:
https://weather.com/swagger-docs/ui/sun/v3/sunV3AlertsWeatherAlertsHeadlines.json
